DROP TABLE IF EXISTS departments;

CREATE TABLE departments
(
    DepartmentId   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DepartmentName varchar(20)
);

DROP TABLE IF EXISTS students;

CREATE TABLE students
(
    StudentId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName varchar(20) NOT NULL,
    LastName varchar(20) NOT NULL,
    DateOfBirth date NOT NULL,
    Address varchar(30) NULL,
    PhoneNumber varchar(10) NULL,
    DepartmentId int NOT NULL,
    CreatedOn TIMESTAMP NOT NULL,
    FOREIGN KEY (DepartmentId) REFERENCES departments (DepartmentId)
);
